jog_arm_server:
  cmd_in_topic:  jog_arm_server/delta_jog_cmds
  incoming_cmd_timeout:  0.25  # Stop jogging if X seconds elapse without a new cmd
  joint_topic:  joint_states
  move_group_name:  right_ur5
  singularity_threshold:  5.5  # Slow down when the condition number hits this (close to singularity)
  hard_stop_singularity_threshold: 12. # Stop when the condition number hits this
  cmd_out_topic:  right_ur5_controller/right_ur5_joint_speed
  planning_frame:  right_ur5_base_link
  low_pass_filter_coeff:  2.  # Larger c --> trust the filtered data more, trust the measurements less.
  pub_period:  0.01  # 1/Nominal publish rate [seconds]
  scale:
    linear:  0.0004
    rotational:  0.0008

# This node republishes joystick messages for the arm jogger.
joy_to_twist:
  cmd_frame:  temoto_end_effector
